### ISSUE TITLE
Report file type consistency

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#12]
The file type for the report "generate events probability" has file type CVS, and should be xlsx for consistency with the "generate cutset" report.

**Comment by juli1** [comment]
Unfortunately, this is not so simple: csv files does not allow to have multiple sheets while the excel (XLS) format does. On the other hand, the csv is more portable and readable: you can basically import it with any tool.
This is why I try to keep the CSV format as much as possible. But for the cutset, I wanted to have the capability to be able to generate one cutset per sheet for very important model.

That is why "one format" does not fit all ... and I am using several formats.

**Comment by fletchwsf** [comment]
Ok I understand.  I was surprised at the use of the xls format, but in this case it makes sense for the cutset report as it enables the report to have multiple sheets.

**Comment by fletchwsf** [comment]
...no point it keeping this one open.
