### ISSUE TITLE
Formatting of leaf nodes

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#15]
The img files for the leaf nodes need to be updated to the "description/event type" format as shown for the "undeveloped" gate. Also the text placement for the updated leaf nodes needs to be top and centered (currently is centered and centered). 

![image](https://cloud.githubusercontent.com/assets/7156576/9157982/06d695c6-3edd-11e5-9d57-6f94fa446736.png)

**Comment by juli1** [comment]
Unfortunately, this is possible to center horizontally but not vertically. For updating the img files, what do you mean? There is a different file for each different event type. Can you elaborate and detail the bug please? Thanks.

**Comment by fletchwsf** [comment]
The node format being centered or border was a limitation that I was not aware of. I will provide a new set of image files for the leaf nodes that is proportioned so the text centered on the nose is readable.

**Comment by juli1** [comment]
Still I do not really understand the issue. I can fix it but for now, do not really understand what it is. Is it possible to describe the issue? Sorry for asking, I am just trying to understand what is wrong. Thanks!

**Comment by fletchwsf** [comment]
The issue is just formatting, and a preference for an image that looks
"more professional".  Having the leaf nodes represented with a circle,
diamond etc., communicates the intend for a basic, or undeveloped
event etc. and will be understood by users.  A more refined FTA look for
leaf nodes has a block for the text, and the symbol for the type of gate
just below block as shown in the image posted earlier.

Given that Sirus doesn't support having text at the top of the node, the
easiest way forward would be with the simple formatting (circle, diamond,
etc.).

**Comment by juli1** [comment]
New pictures integrated in the sources. New release to come
