### ISSUE TITLE
Cutset report should include event probabilities 

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#16]
The cutset report should include the probability of the cutset event.

For example Event E is caused by Event A AND B  or Event C AND D.  When the probabilities are provided for events A,B,C and D, the probability report will list rates for the top event E and two events (A AND B) and (C AND D). The cutset report will show two cutsets with the individual leaf node probabilities, but it should also show the rate for the cutset. 

In the following table, Cutset 0 and Cutset 1 should have a calculated probability on rows 3 and 7 respectively. 

![image](https://cloud.githubusercontent.com/assets/7156576/9240172/44e398c2-4131-11e5-8f96-7ae4933fd0e5.png)

  EMFTA 1.0.0.201508092013  edu.cmu.emfta.feature.feature.group SEI/CMU

**Comment by juli1** [comment]
Fixed in the source, will be pushed with the next release
