### ISSUE TITLE
After calculating probabilities the diagram nodes should show the calculated values 

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#17]
In the following figure, all of the base events have probabilities, and the probability report calculates the event rates. After calculating the rates, the user should have the option to update the fault tree and table view with the calculated probabilities. 

![fta tree](https://cloud.githubusercontent.com/assets/7156576/9240240/03610d84-4132-11e5-92b3-7c8d27108500.jpg)

**Comment by juli1** [comment]
I added a new menu "update probabilities" that do the work. Should be fixed. A new release is available.
