### ISSUE TITLE
Certain event gate types don't display text correctly 

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#18]
EMFTA 1.0.0.201508132201  edu.cmu.emfta.feature.feature.group SEI/CMU

The latest update has the new event gate figures, but certain figures don't display all of their text as shown in the figure below. The event gates are:
- undeveloped
- external 
- conditioning
- intermediate (but only when it is used as a leaf node, which is poor style)

The basic gate displays as expected. I am not sure if the issue is in Sirius or if it has something to do with the original image files. The event gate image files in this update were all prepared in the same manner. Please let me know if I need to generate an updated set. 

![image](https://cloud.githubusercontent.com/assets/7156576/9286336/5d17154c-42bf-11e5-934d-995a561f519b.png)

**Comment by juli1** [comment]
Sorry to ask but is it because we do not see the probability and description? What is wrong with the picture?
