### ISSUE TITLE
New wizard feature copies in data from other fault trees

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#21]
Select a folder that already contains several fault tree files. Create a new emfta model using the wizard, and the wizard populates the new model, with files from an existing model.

In the figure below, the models "test.emfta" and "test04.emfa" were created using the wizard. The wizard populated the models with the model content of "isolette_final..". 

![image](https://cloud.githubusercontent.com/assets/7156576/9286883/c87071e6-42cc-11e5-9c4e-4bfc2d93f97c.png)

**Comment by juli1** [comment]
Is it possible to indicate a list of steps to follow to reproduce the bug? It will help to investigate.

**Comment by fletchwsf** [comment]
Here are the steps.
1. I have a single project folder that contains multiple emfta.design files.
2. Select the top level project folder and use the emfta wizard to create a new design file called "test04".
3. Double click on the "test04.emfta" file and inspect the resource set, the file is populated with events from the "isolette" fault tree.

**Comment by juli1** [comment]
What fault tree did you choose in the wizard? Did you had a look at what you selected (see picture below)?

![wizard](https://cloud.githubusercontent.com/assets/993972/9347075/f72a515e-45f2-11e5-82d9-1a133d50775b.png)

**Comment by fletchwsf** [comment]
...well look at that! A button that copies an example tree into the work
space. Completely missed that setting. Clearly a user bug, and a another
bug report to be closed.

Bill
