### ISSUE TITLE
Possible update site issue with clean install or user error

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#22]
Installed the Eclipse Mars update on the computer, and tried to install emfta using the update site link from the github readme page. Two errors were encountered.

1). With only Eclipse and Sirius installed, installation using the emfta update site, the installation fails because Osate is not installed. Same issue if the Osate bridge check box is left unchecked. 

2) With Eclipse, Sirius, and Osate installed, the installation progresses but fails with the error messages shown below.With the clean Eclipse installation, it looks like the installer is checking for the very first update site versions of the *.jar files. When it can only find the *.jar files from yesterday, the installation fails.

This maybe a user error, i,e,  trying to use Eclipse Mars prior to Osate having a Mars release.

An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta_0.1.0.201506241535.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta_0.1.0.201506241535.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.actions_0.1.0.201506241535.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.actions_0.1.0.201506241535.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.edit_1.0.0.201506241535.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.edit_1.0.0.201506241535.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.editor_1.0.0.201506241535.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.editor_1.0.0.201506241535.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/features/edu.cmu.emfta.feature_1.0.0.201506241535.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/features/edu.cmu.emfta.feature_1.0.0.201506241535.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.tests_1.0.0.201506241535.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/edu.cmu.emfta.tests_1.0.0.201506241535.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/emfta.design_1.0.0.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/emfta.design_1.0.0.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/org.osate.aadl2.errormodel.emfta_1.0.0.201508031632.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/plugins/org.osate.aadl2.errormodel.emfta_1.0.0.201508031632.jar
Artifact not found: https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/features/org.osate.aadl2.errormodel.emfta.feature_1.0.0.201508031632.jar.
https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/features/org.osate.aadl2.errormodel.emfta.feature_1.0.0.201508031632.jar

**Comment by vladgriboff** [comment]
Same issue reproduced under same conditions (Mars Release (4.5.0), Eclipse Modeling Tools with Sirius installed from marketplace).

**Comment by juli1** [comment]
For now, EMFTA does not work on Mars but should work on Luna. I will investigate, try to find why we have this issue and ultimately, try to make it working on Mars.

**Comment by sei-jdelange** [comment]
@vladgriboff and @fletchwsf 

Is it possible to try to update now? If it does not work with Mars, please give a try with Luna. I tried with a new version of Luna, installed sirius and then EMFTA without the OSATE bridge. Please let met know.

Julien.

**Comment by juli1** [comment]
Please try again and let me know if it works now. Should work with Mars.

**Comment by fletchwsf** [comment]
Will try in an hour or two.

**Comment by vladgriboff** [comment]
Julien, thanks a lot for your time!
Unfortunately still getting the same errors with Mars (installing only EMFTA, without the OSATE brdtge).
Will try with Luna, but will need some time, may be in a day or so.

**Comment by juli1** [comment]
Thanks for the update. I will try to update, will test again and let you know! Thanks!

**Comment by juli1** [comment]
Dear @fletchwsf and @vladgriboff ,

I made an update site for Luna and Mars. I started with a clean install for just EMFTA and it seems to work. Please tell me if that works and if it works or not, please tell me the version (Mars or Luna).

Thanks.

Mars update site: https://raw.githubusercontent.com/juli1/emfta/mars/edu.cmu.emfta.updatesite
Luna update site: https://raw.githubusercontent.com/juli1/emfta/luna/edu.cmu.emfta.updatesite

**Comment by vladgriboff** [comment]
Dear Julien,
I am affraid those two links for update sites for mars and luna are broken.

Regards,
Vlad

**Comment by sei-jdelange** [comment]
Can you try 
https://raw.githubusercontent.com/juli1/emfta/mars/edu.cmu.emfta.updatesite/
and
https://raw.githubusercontent.com/juli1/emfta/luna/edu.cmu.emfta.updatesite/

**Comment by fletchwsf** [comment]
Julien,

I uninstalled the prior emfta packages, and installed using the Luna update
site, and emfta downloaded and installed with no issues.

Bill

**Comment by juli1** [comment]
Great! What about the help? Is it included in your installation as well?

**Comment by fletchwsf** [comment]
Julien,

Sorry, but help is still missing. Also searching in help finds zero
results. Here is the version number for reference:
  EMFTA 1.0.0.201508181012 edu.cmu.emfta.feature.feature.group SEI/CMU

Bill

**Comment by sei-jdelange** [comment]
Ok, I found the bug, I fixed it in the sources, it is available in the release for Mars (the master branch).

Julien.
