### ISSUE TITLE
Add a gate type called "intermediate" to the design

### ISSUE THREAD

**Issue by fletchwsf** [juli1/emfta#23]
The current design only allows a gate node as the child of an Intermediate event node. In constructing a fault tree, the analyst will need to introduce a block of text to explain an aspect of the failure path. In the current emfta design the only option to connect to intermediate event nodes is an OR gate is shown in the following picture.

![image](https://cloud.githubusercontent.com/assets/7156576/9346349/b7aea7e0-45e9-11e5-8c43-3db3bda18504.png)

G011 and G012, are two events taken from Figure 10-13 in the NASA "Fault Tree Handbook with Aerospace Applications"

In order to eliminate the OR gate between G011 and G012, the G012 leaf node needs to become an "intermediate gate" node. With this change incorporated the design will have two types of intermediate symbols. An "intermediate event" symbol which is a leaf, and an "intermediate gate" which is a node (aka parent). 

In the above figure, then the "OR" gate would be deleted, and the G012 "intermediate event" node would be changed to an "intermediate gate" node. The other child inputs under G012 can then be added without difficulty.

For calculation of probability and validation, the "intermediate gate" node, copies the value of the connected child, up to the "intermediate gate" node parent.

It maybe possible to delete the "intermediate event" leaf from the design, but it should remain for the time being.

**Comment by juli1** [comment]
This is fixed in the sources. You can update your mars installation using https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/
