### ISSUE TITLE
Can't create EMFTA models

### ISSUE THREAD

**Issue by fmadiot** [juli1/emfta#25]
Hi,
I have installed EMFTA from the marketplace on Eclipse Mars (Eclipse IDE for Java Developers package).
Once installed, I can't find the way to create EMFTA models.
I have tested two ways : from the examples (no EMFTA menu available in the wizard) and by trying to create an empty model from EMF generated wizard (that I didn't find).
Fred

**Comment by juli1** [comment]
What version of Java are you using? Also, when trying the wizard, can you try File->New->Others
There should be a wizard.

**Comment by juli1** [comment]
Any additional information about the bugreport? I would need more information to reproduce and investigate! Thanks!

**Comment by fmadiot** [comment]
The wizard is not visible with File->New->Others (you mean in the category 'Example EMF Model Creation Wizards' ?)
My Java version is 1.7.0_67

**Comment by juli1** [comment]
Under File -> New -> Others, there is then a category called EMFTA Wizard. See below. Can you confirm you do not have it? In that case, can you tell me the version of EMFTA?
![wizard](https://cloud.githubusercontent.com/assets/993972/9578143/9a2af63a-4fb5-11e5-8968-3430e4f4f088.png)

**Comment by fmadiot** [comment]
Yes I confirm that I can't see this category.
I have installed the version from the marketplace
![wizard](https://cloud.githubusercontent.com/assets/2065575/9578271/aecfdea6-4fe8-11e5-819c-fe985206ddcf.png)
![plugins](https://cloud.githubusercontent.com/assets/2065575/9578274/b28dbd9c-4fe8-11e5-8144-bb7fe7a39938.png)

**Comment by juli1** [comment]
Can you try to install java 8, make sure java 8 is used by eclipse (see the preferences) and check if the wizard appears?

**Comment by fmadiot** [comment]
Yes it works with Java 8.
Thanks

**Comment by juli1** [comment]
ok, thanks! I will see if I can lower the dependency and just use it with previous version of Java. For now, the requirement was Java 8.

Thanks again. I will close the bug then.

Julien.
