### ISSUE TITLE
Update site URL on the main page might be wrong

### ISSUE THREAD

**Issue by DreambigOu** [juli1/emfta#29]
First, thank you for making open source tool.

The URL for installing the EMFTA displayed on the main page might be wrong.
"Start OSATE and install EMFTA inside your installation
Once you start OSATE, go in the install menu again and enter the following update site: https://raw.githubusercontent.com/juli1/emfta/luna/edu.cmu.emfta.updatesite/" 

I cannot install with "https://raw.githubusercontent.com/juli1/emfta/luna/edu.cmu.emfta.updatesite/"
Then, I try "https://raw.githubusercontent.com/juli1/emfta/master/edu.cmu.emfta.updatesite/" 
It works on the OSTATE.

**Comment by juli1** [comment]
Since OSATE migrated to Mars, the update site had to change!

Thanks for the notice, I changed it!
